# Generated by Django for Discord Onboarding

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access Discord onboarding'), ('admin_access', 'Can send auth requests to other users')),
                'default_permissions': (),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('discord_id', models.BigIntegerField(help_text='Discord user ID')),
                ('discord_username', models.CharField(help_text='Discord username for reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='Linked Alliance Auth user (after successful auth)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Token',
                'verbose_name_plural': 'Onboarding Tokens',
            },
        ),
    ]